package com.nst.tutorials.rest.responseloggerinjections;

import com.ebay.nst.NSTServiceTestRunner;
import com.ebay.nst.NSTServiceWrapperProcessor;
import com.ebay.runtime.RuntimeConfigManager;
import com.ebay.runtime.RuntimeConfigValue;
import com.ebay.runtime.arguments.IosMocksLocationArgument;
import com.ebay.runtime.arguments.WhatToWriteArguments;
import com.ebay.service.logger.WhatToWrite;
import com.ebay.softassert.EbaySoftAssert;
import com.nst.tutorials.rest.shared.CanadaHoliday;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class ResponseLoggerInjectionsTest implements NSTServiceTestRunner {

    private static final String RESPONSE_LOGGER_INJECTIONS_PATH = "src/test/java/com/nst/tutorials/rest/responseloggerinjections";
    private static final String GENERATED_MOCK_PATH = RESPONSE_LOGGER_INJECTIONS_PATH + "/ResponseLoggerInjectionsTest_exampleResponseLoggerInjectionMockGenerationTest_0_ResponseLoggerInjectionsWrapper.har";

    @BeforeClass
    // Remove any prior mocks that were generated by running the test method below.
    public void removeExistingMock() {
        File existingMock = new File(GENERATED_MOCK_PATH);
        if (existingMock.exists()) {
            existingMock.delete();
            System.out.printf("Removed existing mock at: %s%n", GENERATED_MOCK_PATH);
        }
    }

    @Test
    public void exampleResponseLoggerInjectionMockGenerationTest() throws Exception {
        /**
         * Overriding the `whatToWrite` runtime argument in the pom.xml surefire plugin configuration argument line.
         * Example output is placed in the same directory as this file (mockgeneration).
         */
        RuntimeConfigValue<List<WhatToWrite>> whatToWriteArguments = (RuntimeConfigValue<List<WhatToWrite>>) RuntimeConfigManager.getInstance().getRuntimeArgument(WhatToWriteArguments.KEY);
        List<WhatToWrite> whatToWriteOverride = new ArrayList<>();
        whatToWriteOverride.add(WhatToWrite.MOCKS);
        whatToWriteArguments.override(whatToWriteOverride);

        RuntimeConfigValue<String> whereToWriteArgument = (RuntimeConfigValue<String>) RuntimeConfigManager.getInstance().getRuntimeArgument(IosMocksLocationArgument.KEY);
        whereToWriteArgument.override("src/test/java/com/nst/tutorials/rest/responseloggerinjections");

        NSTServiceWrapperProcessor serviceProcessor = new NSTServiceWrapperProcessor();

        // Send a GET /api/v1/holidays/{holidayId} request.
        ResponseLoggerInjectionsWrapper restServiceWrapperWithResponseLoggerInjection = new ResponseLoggerInjectionsWrapper(CanadaHoliday.CANADA_DAY);
        serviceProcessor.sendRequestAndGetJSONResponse(restServiceWrapperWithResponseLoggerInjection);
    }

    @AfterClass
    // This assertion was added to ensure that mock generation output is successful in this tutorial.
    // This is not a required part of writing an NST test.
    public void ensureMockIsGeneratedSuccessfully() {
        File existingMock = new File(GENERATED_MOCK_PATH);
        Assert.assertTrue(existingMock.exists());
    }

    @Override
    public EbaySoftAssert getSoftAssert() {
        return null;
    }
}
