package com.nst.tutorials.rest.mockgeneration;

import com.ebay.nst.NSTServiceTestRunner;
import com.ebay.nst.NSTServiceWrapperProcessor;
import com.ebay.runtime.RuntimeConfigManager;
import com.ebay.runtime.RuntimeConfigValue;
import com.ebay.runtime.arguments.WhatToWriteArguments;
import com.ebay.service.logger.WhatToWrite;
import com.ebay.softassert.EbaySoftAssert;
import com.nst.tutorials.rest.shared.CanadaHoliday;
import com.nst.tutorials.rest.shared.GenericServiceWrapper;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class MockGenerationTest implements NSTServiceTestRunner {

    private static final String GENERATED_MOCK_PATH = RuntimeConfigManager.getInstance().getIosMocksLocation() + "/MockGenerationTest_exampleMockGenerationTest_0_GenericServiceWrapper.json";

    @BeforeClass
    // Remove any prior mocks that were generated by running the test method below.
    public void removeExistingMock() {
        File existingMock = new File(GENERATED_MOCK_PATH);
        if (existingMock.exists()) {
            existingMock.delete();
            System.out.printf("Removed existing mock at: %s%n", GENERATED_MOCK_PATH);
        }
    }

    @Test
    public void exampleMockGenerationTest() throws Exception {
        /**
         * Overriding the `whatToWrite` runtime argument in the pom.xml surefire plugin configuration argument line.
         * Example output is placed in the same directory as this file (mockgeneration).
         */
        RuntimeConfigValue<List<WhatToWrite>> whatToWriteArguments = (RuntimeConfigValue<List<WhatToWrite>>) RuntimeConfigManager.getInstance().getRuntimeArgument(WhatToWriteArguments.KEY);
        List<WhatToWrite> whatToWriteOverride = new ArrayList<>();
        whatToWriteOverride.add(WhatToWrite.MOCKS);
        whatToWriteArguments.override(whatToWriteOverride);

        NSTServiceWrapperProcessor serviceProcessor = new NSTServiceWrapperProcessor();

        // Send a GET /api/v1/holidays/{holidayId} request.
        GenericServiceWrapper restServiceWrapper = new GenericServiceWrapper(CanadaHoliday.CANADA_DAY);
        serviceProcessor.sendRequestAndGetJSONResponse(restServiceWrapper);
    }

    @AfterClass
    // This assertion was added to ensure that mock generation output is successful in this tutorial.
    // This is not a required part of writing an NST test.
    public void ensureMockIsGeneratedSuccessfully() {
        File existingMock = new File(GENERATED_MOCK_PATH);
        Assert.assertTrue(existingMock.exists());
    }

    @Override
    public EbaySoftAssert getSoftAssert() {
        return null;
    }
}
