//
// PointsRedemptionIncentives.swift
// eBay
//
// Created by <author> on 11/15/19.
// Copyright 2019 eBay. All rights reserved.
// TestRail Link: https://testrail.m3.ebay.com/index.php?/suites/view/19645
//

import XCTest
import AutoGeneratedInput

class SimpleCheckoutExampleTest : ServiceTestBase {
    
    // AUTO GENERATED MEMBER FIELD CODE BLOCK - DO NOT MODIFY CONTENTS
    let xoHubPageModel = XoHubPageModel()
    let pspPageModel = PspPageModel()
    let xoSuccessPageModel = XoSuccessPageModel()
    // END OF AUTO GENERATED MEMBER FIELD CODE BLOCK
    
    func test_firstTest() {
        
          // AUTO GENERATED MOCK INJECTION CODE BLOCK - DO NOT MODIFY CONTENTS
          inject(responses: [
              "PaymentsModule.CreateCheckoutSessionRequest_1": "SimpleCheckoutExampleTest_firstTest_1_CreateCheckoutSessionV2.har",
              "PaymentsModule.SetPaymentRequest_2": "SimpleCheckoutExampleTest_firstTest_2_SetPayment.har",
              "PaymentsModule.PurchaseCheckoutSessionRequest_3": "SimpleCheckoutExampleTest_firstTest_3_PurchaseCheckoutSession.har"
              ])
          // END OF AUTO GENERATED MOCK INJECTION CODE BLOCK

            // AUTO GENERATED METHOD CODE BLOCK - DO NOT MODIFY CONTENTS
            // CORRESPONDING API CALL: CreateCheckoutSessionV2
            // OPERATION INDEX: 1
            xoHubPageModel.enterCheckout()
            // END OF AUTO GENERATED METHOD CODE BLOCK

            // AUTO GENERATED METHOD CODE BLOCK - DO NOT MODIFY CONTENTS
            // CORRESPONDING API CALL: SetPayment
            // OPERATION INDEX: 2
            xoHubPageModel.navigateToPspPage()
            pspPageModel.addNewPaymentInstrument()
            // END OF AUTO GENERATED METHOD CODE BLOCK
        
        xoHubPageModel.validate()
        
          // AUTO GENERATED METHOD CODE BLOCK - DO NOT MODIFY CONTENTS
          // CORRESPONDING API CALL: PurchaseCheckoutSessionV2
          // OPERATION INDEX: 3
          xoHubPageModel.purchase()
          xoSuccessPageModel.confirmPurchaseComplete()
          // END OF AUTO GENERATED METHOD CODE BLOCK
        
        xoSuccessPageModel.extraSpecificValidation()
    }
    
    func test_secondTest() {
        testRailCaseId = "2027566"
        XCTAssert(false, "Unimplemented test.")
    }
    
    func test_thirdTest() {
        testRailCaseId = "2027567"
        XCTAssert(false, "Unimplemented test.")
    }
    
    
}
